apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-api
  labels:
    app: media-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-api
  template:
    metadata:
      labels:
        app: media-api
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=IMAGO API - Hello"
        ports:
          - containerPort: 5678
        env:
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch.elasticsearch.svc.cluster.local:9200"

