apiVersion: v1
kind: Service
metadata:
  name: media-api-svc
spec:
  type: NodePort
  selector:
    app: media-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5678
      nodePort: 30080

