---
- name: Install Zabbix Agent on Ubuntu/Debian
  hosts: all
  become: yes
  tasks:

    - name: Add Zabbix repository key
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Add Zabbix repository
      apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
        state: present
        filename: zabbix

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: Ensure zabbix-agent service is started and enabled
      service:
        name: zabbix-agent
        state: started
        enabled: yes

